#!/bin/bash

branch_name=$(git symbolic-ref -q HEAD)
branch_name=${branch_name##refs/heads/}
branch_name=${branch_name:-HEAD}

git diff HEAD --stat
printf "\n"
git status

blue=$(tput setaf 6)
normal=$(tput sgr0)

printf "%40s\n\n" "${blue}Have you prefixed your commit message with JIRA ticket reference?${normal}"
printf "\nDo you wish to commit on branch ${branch_name}?\nThe commit message is: ${1}\n"

select yn in "Yes" "No"; do
	case $yn in
		Yes )
				find . -name ".DS_Store" -print0 | xargs -0 rm -rf
				find . -name "._*" -print0 | xargs -0 rm -rf

				# Runs all the git commands

				git add -A
				git commit -m "${1}"

				break;;
		No )
				echo "Ok, maybe next time :-)"
				exit;;
	esac
done
